version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password  # Password for the root user (not recommended for production)
      MYSQL_DATABASE: my_spring_db        # Name of the database to create
      MYSQL_USER: your-username           # User to access the database
      MYSQL_PASSWORD: your-password       # Password for the above user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql         # Persist MySQL data
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data                  # Persist Redis data
    command: redis-server --requirepass "your-password" --appendonly yes
volumes:
  mysql_data:
  redis_data: