db.mysql.url=jdbc:mysql://localhost:3306/template?createDatabaseIfNotExist=true&&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.mysql.username=your-username
db.mysql.password=your-password