db.mysql.url=jdbc:mysql://localhost:3306/template?createDatabaseIfNotExist=true&&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.mysql.username=your-username
db.mysql.password=your-password
db.redis.host=localhost
db.redis.port=6379
db.redis.password=your-password
security.jwt.secret=your-secret-key-must-be-64-characters-for-hs256
security.jwt.access.token.expire=30m