db.mysql.url=jdbc:mysql://localhost:3306/template?createDatabaseIfNotExist=true&&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.mysql.username=your-username
db.mysql.password=your-password
db.redis.host=localhost
db.redis.port=6379
db.redis.password=your-password
security.jwt.secret=your-secret-key-must-be-64-characters-for-hs256
security.jwt.access.token.expiration=30m
cloudinary.cloud.name=dp32nbhts
cloudinary.api.key=834589124622873
cloudinary.api.secret=YA6UqMLX1MJSs-oCQhqPJx2P7NU
cloadinary.folder=spring-template
mail.host=localhost
mail.port=1025
mail.username=test@gmail.com
mail.password=
admin.username=admin
admin.password=admin
admin.first.name=Amin
admin.last.name=User
admin.email=admin@email.com