spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cloudinary:
  cloud-name: your-cloud-name
  api-key: your-api-key
  api-secret: your-api-secret
  folder-name: your-folder-name
