plugins {
    id 'java-library'
}

bootJar { enabled = false }
jar { enabled = true }

bootRun {
    enabled = false
}

dependencies {
    api libs.spring.boot.starter.web
    api libs.spring.boot.starter.data.jpa
    api libs.spring.boot.starter.validation
    runtimeOnly libs.mysql.connector

    // Swagger
    implementation libs.spring.boot.starter.webmvc
    implementation libs.springdoc.openapi.ui

    // Redis
    api libs.spring.boot.starter.data.redis
}