spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 1000ms

      lettuce:
        pool:
          max-active: 4
          max-idle: 2
          min-idle: 0
          max-wait: 500ms
          time-between-eviction-runs: 10s

app:
  api:
    prefix: /api
    default-version: v1
    supported-versions:
      - v1
  security:
    public-urls:
      - ${app.api.prefix}/${app.api.default-version}/auth/**
      - ${app.api.prefix}/${app.api.default-version}/public/**
      - /actuator/health
      - /actuator/info
      - /v3/api-docs
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
  jwt:
    secret: ${JWT_SECRET}
    access-token-expire: ${JWT_ACCESS_TOKEN_EXPIRE}
