plugins {
}

bootJar { enabled = false }
jar { enabled = true }

bootRun {
    enabled = false
}

dependencies {
    implementation project(':shared')
    implementation project(':security')
    implementation project(':file')

    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
}
